# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChmodCli < Formula
  desc "Simple TUI to interact with the chmod command."
  homepage "https://github.com/Mayowa-Ojo/chmod-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.2.0/chmod-cli_0.2.0_Darwin_arm64.tar.gz"
      sha256 "89ae14e603c314ae1cde240b5364b584f9a92470f9a531148479e93028936042"

      def install
        bin.install "chmod-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.2.0/chmod-cli_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "3ac697e8d43b4ac839c6635e13d4557a0b3d3c6159e66d8e85cfc3ee7ad47063"

      def install
        bin.install "chmod-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.2.0/chmod-cli_0.2.0_Linux_x86_64.tar.gz"
      sha256 "fd9e2d67253e5864a949417e29ac85ba0558be2c220456f1cc01dc835088dab5"

      def install
        bin.install "chmod-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.2.0/chmod-cli_0.2.0_Linux_arm64.tar.gz"
      sha256 "0d157c512c99780437401a9365b47cdc9d06b4a842064d5facdc471b5dfb4cd1"

      def install
        bin.install "chmod-cli"
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
