# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChmodCli < Formula
  desc "Simple TUI to interact with the chmod command."
  homepage "https://github.com/Mayowa-Ojo/chmod-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.1.0/chmod-cli_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a5615445864736afaeb356975988a82f483bfa22dbeaceb6be4eaf586168aa32"

      def install
        bin.install "chmod-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.1.0/chmod-cli_0.1.0_Darwin_arm64.tar.gz"
      sha256 "bd5956fe0cbd9292780bf697b01a91bd41e2ed5334c7517c68469589f51051cc"

      def install
        bin.install "chmod-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.1.0/chmod-cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "0a7bc835888d0d6c9f0f33a433b45e6f71eb94712855c49933f3d42ee9de561d"

      def install
        bin.install "chmod-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Mayowa-Ojo/chmod-cli/releases/download/v0.1.0/chmod-cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "e6d0c361c3f1261f6dadaab275b91ddd8efe5dfea3ac1816626f79583846f05c"

      def install
        bin.install "chmod-cli"
      end
    end
  end

  test do
    system "#{bin}/program --version"
  end
end
